/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SnsIndexLazyImport = createFileRoute('/sns/')()
const RoomIndexLazyImport = createFileRoute('/room/')()
const ProfileIndexLazyImport = createFileRoute('/profile/')()
const PortfolioIndexLazyImport = createFileRoute('/portfolio/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SnsIndexLazyRoute = SnsIndexLazyImport.update({
  path: '/sns/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sns/index.lazy').then((d) => d.Route))

const RoomIndexLazyRoute = RoomIndexLazyImport.update({
  path: '/room/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/room/index.lazy').then((d) => d.Route))

const ProfileIndexLazyRoute = ProfileIndexLazyImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))

const PortfolioIndexLazyRoute = PortfolioIndexLazyImport.update({
  path: '/portfolio/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfolio/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sns/': {
      id: '/sns/'
      path: '/sns'
      fullPath: '/sns'
      preLoaderRoute: typeof SnsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  PortfolioIndexLazyRoute,
  ProfileIndexLazyRoute,
  RoomIndexLazyRoute,
  SnsIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/portfolio/",
        "/profile/",
        "/room/",
        "/sns/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/portfolio/": {
      "filePath": "portfolio/index.lazy.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.lazy.tsx"
    },
    "/room/": {
      "filePath": "room/index.lazy.tsx"
    },
    "/sns/": {
      "filePath": "sns/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
