name: Update RSS JSON file

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 1日1回 (午前0時) に実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # すべての履歴をフェッチして変更を記録

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x # プロジェクトに合わせて Node.js のバージョンを変更

      - name: Install dependencies
        run: npm install

      - name: Update RSS Feeds
        run: npm run update-rss

      - name: Commit and push RSS update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/rss/data.json
          if [ -n "$(git status -s)" ]; then
            git commit -m "Update RSS JSON file $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
