name: Update RSS JSON file

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 毎日午前0時に実行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # GITHUB_TOKENに書き込み権限を付与
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: pnpm install

      - name: Update RSS Feeds
        run: pnpm run update-rss

      - name: Commit and push RSS update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/rss/data.json
          if [ -n "$(git status -s)" ]; then
            git commit -m "Update RSS JSON file $(date +'%Y-%m-%d %H:%M:%S')"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
